adminUser:
  password: vault:ckrych3/adminUser:password
  username: corinnekrych
enableDocker: false
pipelineUser:
  email: corinnekrych@gmail.com
  token: vault:ckrych3/pipelineUser:token
  username: corinnekrych
prow:
  hmacToken: vault:ckrych3/prow:hmacToken
